/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: 'class',
  theme: {
    extend: {
      // Spacing - 4px base unit (Stitch Design System)
      spacing: {
        'unit': '4px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'section-lg': '8rem',
        'section-md': '6rem',
      },
      // Colors - Stitch Design System (Light + Dark)
      colors: {
        // Light theme (default)
        background: '#FCF9F4',
        'background-dim': '#DCDAD5',
        'background-bright': '#FCF9F4',
        surface: '#FCF9F4',
        'surface-bright': '#FCF9F4',
        'surface-dim': '#DCDAD5',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F6F3EE',
        'surface-container': '#F0EDE9',
        'surface-container-high': '#EBE8E3',
        'surface-container-highest': '#E5E2DD',
        'surface-variant': '#E5E2DD',
        'on-surface': '#1C1C19',
        'on-surface-variant': '#4F4537',
        'inverse-surface': '#31302D',
        'inverse-on-surface': '#F3F0EB',
        outline: '#817565',
        'outline-variant': '#D4C4B0',
        'surface-tint': '#7E5700',
        primary: '#5F4100',
        'on-primary': '#FFFFFF',
        'primary-container': '#7E5700',
        'on-primary-container': '#FFD289',
        'inverse-primary': '#F2BE65',
        'primary-fixed': '#FFDEAC',
        'primary-fixed-dim': '#F2BE65',
        'on-primary-fixed': '#281900',
        'on-primary-fixed-variant': '#5F4100',
        secondary: '#366286',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#A8D3FD',
        'on-secondary-container': '#2F5B7F',
        'secondary-fixed': '#CDE5FF',
        'secondary-fixed-dim': '#A0CBF4',
        'on-secondary-fixed': '#001D32',
        'on-secondary-fixed-variant': '#1A4A6D',
        tertiary: '#8F1301',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#B12D17',
        'on-tertiary-container': '#FFCDC4',
        'tertiary-fixed': '#FFDAD3',
        'tertiary-fixed-dim': '#FFB4A5',
        'on-tertiary-fixed': '#3F0400',
        'on-tertiary-fixed-variant': '#8E1201',
        error: '#BA1A1A',
        'on-error': '#FFFFFF',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',
        success: '#2D7A4F',
        'on-success': '#FFFFFF',
        'success-container': '#A5F3C5',
        'on-success-container': '#003A1A',
        // Semantic brand colors
        'pharaoh-gold': '#C8922A',
        'nile-blue': '#1B4B6E',
        'papyrus-green': '#2D7A4F',
        obsidian: '#141008',
        'sand-dark': '#1E1810',

        // Dark theme
        dark: {
          background: '#141008',
          'background-dim': '#1E1810',
          'background-bright': '#1C1A14',
          surface: '#1C1A14',
          'surface-bright': '#1C1A14',
          'surface-dim': '#1E1810',
          'surface-container-lowest': '#1E1810',
          'surface-container-low': '#222019',
          'surface-container': '#2C2A23',
          'surface-container-high': '#31302D',
          'surface-container-highest': '#3A3833',
          'surface-variant': '#3A3833',
          'on-surface': '#E8E4DD',
          'on-surface-variant': '#D4C4B0',
          'inverse-surface': '#FCF9F4',
          'inverse-on-surface': '#1C1C19',
          outline: '#9C8F7C',
          'outline-variant': '#504536',
          'surface-tint': '#F8BC51',
          primary: '#F8BC51',
          'on-primary': '#462F00',
          'primary-container': '#5F4100',
          'on-primary-container': '#FFD289',
          'inverse-primary': '#7E5700',
          'primary-fixed': '#FFDEAC',
          'primary-fixed-dim': '#F2BE65',
          'on-primary-fixed': '#281900',
          'on-primary-fixed-variant': '#5F4100',
          secondary: '#A0CBF4',
          'on-secondary': '#003353',
          'secondary-container': '#1A4A6D',
          'on-secondary-container': '#CDE5FF',
          'secondary-fixed': '#CDE5FF',
          'secondary-fixed-dim': '#A0CBF4',
          'on-secondary-fixed': '#001D32',
          'on-secondary-fixed-variant': '#1A4A6D',
          tertiary: '#FFB4A5',
          'on-tertiary': '#690400',
          'tertiary-container': '#8E1201',
          'on-tertiary-container': '#FFDAD3',
          'tertiary-fixed': '#FFDAD3',
          'tertiary-fixed-dim': '#FFB4A5',
          'on-tertiary-fixed': '#3F0400',
          'on-tertiary-fixed-variant': '#8E1201',
          error: '#FFB4AB',
          'on-error': '#690005',
          'error-container': '#93000A',
          'on-error-container': '#FFDAD6',
          success: '#8FD98F',
          'on-success': '#0A3D0E',
          'success-container': '#0A3D0E',
          'on-success-container': '#A5F3C5',
          'pharaoh-gold': '#C8922A',
          'nile-blue': '#1B4B6E',
          'papyrus-green': '#2D7A4F',
          obsidian: '#141008',
          'sand-dark': '#1E1810',
        },
      },
      // Typography - Stitch Design System
      fontFamily: {
        // English
        'headline': ['Playfair Display', 'serif'],
        'headline-medium': ['Playfair Display', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'body-medium': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        // Arabic
        'headline-ar': ['Noto Naskh Arabic', 'serif'],
        'body-ar': ['Cairo', 'sans-serif'],
        'label-ar': ['Cairo', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.05em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      // Border radius - Stitch Design System (ROUND_EIGHT base = 8px)
      borderRadius: {
        none: '0',
        sm: '4px',      // ROUND_FOUR
        DEFAULT: '8px', // ROUND_EIGHT - base unit
        md: '8px',      // ROUND_EIGHT
        lg: '12px',     // ROUND_TWELVE
        xl: '16px',     // Standard cards
        '2xl': '24px',  // Hero sections, modals
        '3xl': '32px',  // Large containers
        full: '9999px', // Pills, avatars, buttons
      },
      // Shadows - Stitch Design System
      boxShadow: {
        none: 'none',
        resting: '0 4px 20px -2px rgba(80, 69, 54, 0.1)',
        hover: '0 8px 30px -4px rgba(126, 87, 0, 0.15)',
        raised: '0 16px 48px -8px rgba(20, 16, 8, 0.25)',
        overlay: '0 24px 64px -12px rgba(20, 16, 8, 0.3)',
        'glow-gold': '0 0 20px rgba(248, 188, 81, 0.4)',
        'glow-gold-subtle': '0 0 12px rgba(200, 146, 42, 0.2)',
        'glow-nile-blue': '0 0 16px rgba(54, 98, 134, 0.3)',
        inner: 'inset 0 -2px 4px rgba(20, 16, 8, 0.1)',
      },
      // Animation durations
      transitionDuration: {
        'fast': '150ms',
        'normal': '250ms',
        'slow': '350ms',
        'slower': '500ms',
      },
      // Animation easing
      transitionTimingFunction: {
        'ease-out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'ease-out-quint': 'cubic-bezier(0.23, 1, 0.32, 1)',
        'ease-out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}