/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light theme (default)
        background: '#FCF9F4',
        surface: '#FFFFFF',
        'surface-container': '#F0EDE9',
        'surface-container-high': '#EBE8E3',
        'on-surface': '#1C1C19',
        'on-surface-variant': '#504536',
        outline: '#827564',
        'outline-variant': '#D4C4B0',
        primary: '#7E5700',
        'on-primary': '#FFFFFF',
        'primary-container': '#C8922A',
        'on-primary-container': '#462F00',
        'primary-fixed': '#FFDEAB',
        'primary-fixed-dim': '#F8BC51',
        secondary: '#366286',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#A8D3FD',
        'on-secondary-container': '#2F5B7F',
        'secondary-fixed': '#CDE5FF',
        'secondary-fixed-dim': '#A0CBF4',
        tertiary: '#B12D17',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#FF6E53',
        'on-tertiary-container': '#6B0A00',
        error: '#BA1A1A',
        'on-error': '#FFFFFF',
        success: '#2E7D32',
        'on-success': '#FFFFFF',
        'pharaoh-gold': '#C8922A',
        'nile-blue': '#1B4B6E',
        'papyrus-green': '#2D7A4F',
        obsidian: '#141008',
        'sand-dark': '#1E1810',
      },
    },
  },
  plugins: [],
}